import Header from '@/features/shared/components/Header';
import SmoothScroll from '@/features/shared/components/global/ScrollSmoother';
import { LuxuryCursor } from '@/features/shared/components/LuxuryCursor';
import { SoundController } from '@/features/shared/components/SoundController';
import Link from 'next/link';

export default function BlogPage() {
  return (
    <>
      <LuxuryCursor />
      <SoundController />
      <Header />
      <SmoothScroll>
        <article className="pt-28 pb-20 min-h-screen">

          <section className="relative py-16 sm:py-24 overflow-hidden bg-gradient-to-br from-[#1a0a0a] via-[#2d0a0a] to-nidra-indigo/95 mb-12">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,80,80,0.12),transparent_60%)]" />
            <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-red-500/40 to-transparent" />
            <div className="absolute bottom-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-red-500/40 to-transparent" />
            <div className="container mx-auto px-4 sm:px-6 relative z-10">
              <div className="absolute top-0 right-4 sm:right-10 w-28 h-28 sm:w-36 sm:h-36 opacity-25 pointer-events-none">
                <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                  <rect x="20" y="20" width="60" height="60" rx="4" fill="none" stroke="#ef4444" strokeWidth="1.5" opacity="0.6"/>
                  <line x1="30" y1="50" x2="70" y2="50" stroke="#ef4444" strokeWidth="0.8" opacity="0.4"/>
                  <line x1="50" y1="30" x2="50" y2="70" stroke="#ef4444" strokeWidth="0.8" opacity="0.4"/>
                  <circle cx="50" cy="50" r="5" fill="#ef4444" opacity="0.7"><animate attributeName="opacity" values="0.3;1;0.3" dur="2s" repeatCount="indefinite"/></circle>
                  <circle cx="50" cy="50" r="44" fill="none" stroke="#E8B960" strokeWidth="0.7" opacity="0.3"><animateTransform attributeName="transform" type="rotate" from="0 50 50" to="360 50 50" dur="30s" repeatCount="indefinite"/></circle>
                </svg>
              </div>
              <Link href="/insights" className="inline-flex items-center text-prakash-gold hover:text-sacred-saffron mb-4 text-sm transition-colors">
                <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7"/></svg>
                Back to Archives
              </Link>
              <div className="flex items-center gap-3 text-sm text-white/50 mb-4">
                <span className="bg-red-500/20 text-red-300 px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider">Geopathic Stress</span>
                <span className="w-1 h-1 bg-white/30 rounded-full" /><span>11 min read</span>
                <span className="w-1 h-1 bg-white/30 rounded-full" /><span>By Vastuvid KK Nagaich</span>
              </div>
              <h1 className="font-serif text-3xl sm:text-4xl md:text-5xl lg:text-6xl text-white leading-tight mb-4">
                Geopathic Stress —{' '}
                <span className="bg-gradient-to-r from-red-400 via-prakash-gold to-sacred-saffron bg-clip-text text-transparent">The Hidden Enemy Affecting Your Health</span>
              </h1>
              <p className="text-lg text-white/60 max-w-3xl">How underground water veins, fault lines, mineral deposits, and EMF radiation silently compromise your immune system — and the precise, non‑invasive Vedic remedies that neutralise them, backed by European research and 20 years of clinical practice.</p>
            </div>
          </section>

          <div className="container mx-auto px-4 sm:px-6 max-w-4xl"><div className="prose prose-lg prose-stone max-w-none">

<p className="lead text-xl text-nidra-indigo/70 leading-relaxed">You have moved into a beautiful home. The Vastu directions are correct. The colours are balanced. The clutter is cleared. And yet — you sleep poorly, wake exhausted, fall ill more often than seems normal, and cannot explain why. The children are repeatedly sick. The couple struggles to conceive. Doctors find nothing wrong. The answer may lie not in the visible structure of your home but in the invisible forces beneath it — a phenomenon known as <strong>geopathic stress</strong>. First identified in Europe in the 1920s by German dowser Baron Gustav von Pohl, who mapped cancer clusters in the Bavarian town of Vilsbiburg and found that every single cancer patient in the town slept above an underground water vein intersection, geopathic stress is now studied by the International Association of Geopathology and the Geo‑Environmental Research Institute. This article presents the complete framework for understanding, detecting, and neutralising geopathic stress — grounded in European research, Vedic Bhumi Dosha science, and two decades of clinical practice by Vastuvid K.K. Nagaich.</p>

<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-red-500 to-kumkuma-red" /><h2 className="font-serif text-2xl sm:text-3xl text-nidra-indigo">What Is Geopathic Stress? The Science of Underground Energy Disturbance</h2></div>
<p>Geopathic stress refers to natural or man‑made radiation emanating from the earth that disrupts the human body's electromagnetic field when a person spends prolonged periods above the source. The term comes from the Greek words <em>geo</em> (earth) and <em>pathos</em> (suffering) — literally "earth suffering." The Geo‑Environmental Research Institute defines it as "the study of the impact of earth radiation on the health of all living organisms." Baron von Pohl's 1929 Vilsbiburg study was groundbreaking: he identified underground water vein crossings with nothing but a dowsing rod, and when the town's medical records were subsequently checked, every one of the 54 cancer deaths in the town had occurred in beds located precisely above the crossings he had mapped. The German medical doctor Ernst Hartmann later confirmed these findings and developed the Hartmann Grid theory — a global network of electromagnetic field lines running north‑south and east‑west, with intersections creating measurable zones of geopathic disturbance.</p>
<p>In the Vedic tradition, these underground disturbances have been recognised for millennia as <strong>Bhumi Dosha</strong> — land impurities that must be neutralised before construction. The Mayamatam, one of the foundational texts of Vastu Shastra alongside the Manasara and Brihat Samhita, devotes entire chapters to Bhumi Pariksha (land examination) — prescribing specific tests for soil quality, underground water veins, and buried objects. What European researchers began documenting in the 1920s, Vedic architects had been addressing for over 2,000 years.</p></div>

<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-amber-500 to-orange-600" /><h2 className="font-serif text-2xl sm:text-3xl text-nidra-indigo">What Causes Geopathic Stress? The Four Primary Sources</h2></div>
<p>Geopathic stress originates from multiple sources, both natural and man‑made. The Geo‑Environmental Research Institute catalogs four primary categories, and the VastuEnergy portal (2025) provides detailed descriptions of each:</p>
<div className="mt-4 space-y-4">
{[{source:'Underground Water Veins',detail:'Moving underground water generates a measurable electromagnetic field through friction between water and rock strata. Where two or more veins intersect, the field intensity multiplies — creating zones of geopathic disturbance. In Vedic Vastu, underground streams are considered a type of Bhumi Dosha that must be identified before construction. Dowsing with copper L‑rods remains the most reliable detection method.'},{source:'Geological Fault Lines',detail:'Fractures in the earth\'s crust emit radioactive gases (primarily radon) and low‑frequency electromagnetic radiation. The World Health Organization identifies radon as the second leading cause of lung cancer globally. Building a home directly above a fault line exposes residents to continuous low‑level radiation that accumulates over decades.'},{source:'Mineral Deposits',detail:'Concentrated deposits of iron, copper, nickel, and other metallic minerals create localised magnetic anomalies. These can distort the Earth\'s natural magnetic field directly beneath a home, interfering with the human body\'s own electromagnetic regulation. Iron‑ore deposits are particularly potent and can be detected through geomagnetic surveys.'},{source:'Man‑Made EMF Radiation',detail:'Power lines, electrical substations, 5G towers, Wi‑Fi routers, and mobile phones generate electromagnetic fields that compound natural geopathic stress. The term "technopathic stress" has emerged to describe the cumulative effect of man‑made radiation superimposed on natural earth energies. The EMF Research Foundation notes that sleeping within 3 metres of a Wi‑Fi router or electrical panel measurably disrupts melatonin production.'},].map((r,i)=>(<div key={i} className="p-5 bg-gradient-to-r from-white to-vastu-stone/20 rounded-2xl border border-prakash-gold/10"><div className="flex items-start gap-3"><div className="w-2.5 h-2.5 rounded-full bg-red-500 mt-1.5 flex-shrink-0"/><div><h3 className="font-serif text-lg text-nidra-indigo font-bold mb-2">{r.source}</h3><p className="text-sm text-nidra-indigo/70 leading-relaxed">{r.detail}</p></div></div></div>))}</div></div>

<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-red-400 to-pink-600" /><h2 className="font-serif text-2xl sm:text-3xl text-nidra-indigo">How Geopathic Stress Affects Your Health — The Research Evidence</h2></div>
<p>The physiological mechanism is increasingly well‑understood. The human body operates on its own electromagnetic system — the heart generates an electrical field measurable meters from the body, and the brain produces electromagnetic oscillations that define sleep stages, mood, and cognitive function. When a person sleeps or works for 6‑8 hours daily above a geopathic stress zone, the external radiation interferes with the body's internal electromagnetic regulation. The VAASTU International portal (2025) summarises the documented health effects:</p>
<div className="mt-4 overflow-hidden rounded-2xl border border-prakash-gold/15">
<table className="w-full text-sm"><thead><tr className="bg-gradient-to-r from-red-500/10 to-orange-500/10"><th className="py-3 px-4 text-left font-serif text-nidra-indigo">System Affected</th><th className="py-3 px-4 text-left font-serif text-nidra-indigo">Documented Effects</th><th className="py-3 px-4 text-left font-serif text-nidra-indigo">Research Source</th></tr></thead><tbody>
{[['Immune System','Chronic fatigue, repeated infections, slow recovery from illness, autoimmune flare‑ups','Geo‑Environmental Research Institute; VAASTU International 2025'],['Sleep','Insomnia, restless sleep, nightmares, waking exhausted despite adequate hours, bed‑wetting in children','Baron von Pohl (1929); Hartmann Grid studies; EMF Research Foundation'],['Neurological','Brain fog, difficulty concentrating, memory problems, depression, anxiety, unexplained irritability','International Association of Geopathology; Geo‑Environmental Research Institute'],['Reproductive','Unexplained infertility, recurrent miscarriages, difficulty conceiving, menstrual irregularities','Multiple European case studies; von Pohl documented clusters'],['Oncological','Higher incidence of cancers, particularly leukaemia and lymphoma, in homes above water vein crossings','Von Pohl Vilsbiburg study (54 cancer cases); WHO radon risk data'],['Pediatric','Children who repeatedly fall ill, slow development, behavioural issues, resistance to medical treatment','VAASTU International; Geo‑Environmental Research Institute'],].map((r,i)=>(<tr key={i} className={`border-t border-prakash-gold/10 ${i%2===0?'bg-white/40':'bg-vastu-stone/20'}`}><td className="py-3 px-4 font-medium text-nidra-indigo/80">{r[0]}</td><td className="py-3 px-4 text-nidra-indigo/60 text-xs">{r[1]}</td><td className="py-3 px-4 text-nidra-indigo/40 text-xs">{r[2]}</td></tr>))}</tbody></table></div>
<p className="mt-3 text-xs text-nidra-indigo/40">Sources: International Association of Geopathology (2025); Geo‑Environmental Research Institute; VAASTU International "Geopathic Stress Analysis" (2025); Baron von Pohl, "Earth Currents as Pathogenic Agents" (1932); WHO Radon and Health Fact Sheet (2025).</p></div>

<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-emerald-400 to-green-600" /><h2 className="font-serif text-2xl sm:text-3xl text-nidra-indigo">Detection Methods — How to Know If Your Home Is Affected</h2></div>
<p>Detecting geopathic stress requires a combination of traditional Vedic techniques and modern electronic instruments. Vastuvid K.K. Nagaich employs a multi‑modal detection protocol refined over two decades:</p>
<div className="mt-4 space-y-4">
{[{method:'Copper L‑Rod Dowsing',desc:'The oldest and most reliable method. Two copper L‑shaped rods, held loosely in each hand, cross involuntarily when passing over underground water veins, fault lines, or mineral deposits. Baron von Pohl used this exact technique to map the Vilsbiburg cancer clusters. Vastuvid K.K. Nagaich has trained in dowsing under three separate Guru‑Shishya lineages.'},{method:'Geomagnetometer (Gauss Meter)',desc:'Measures local magnetic field strength in microtesla (µT). Normal background fields are 25‑65 µT. Geopathic stress zones typically show readings above 100 µT or sharp fluctuations within a small area. The instrument provides quantitative data that validates traditional dowsing results.'},{method:'EMF Meter',desc:'Measures electromagnetic field radiation from man‑made sources: power lines, electrical wiring, Wi‑Fi routers, mobile towers. Readings above 0.4 µT for prolonged exposure are considered potentially harmful by the WHO\'s International Agency for Research on Cancer. Combined with a Gauss meter, this provides a complete picture of both natural and man‑made geopathic radiation.'},{method:'Radon Detector',desc:'Radon is a colourless, odourless radioactive gas that seeps from geological fault lines and certain rock types. Granite‑rich regions are particularly susceptible. The WHO identifies radon as the second leading cause of lung cancer globally. Radon detectors placed for 48‑72 hours provide accurate readings for basement and ground‑floor rooms.'},{method:'Thermal Imaging',desc:'Geopathic stress zones often appear as temperature anomalies in walls and floors due to underground water flow. Thermal imaging cameras detect these anomalies and provide visual confirmation of disturbance zones that correlate with dowsing and magnetometer readings.'},].map((r,i)=>(<div key={i} className="p-5 bg-gradient-to-r from-white to-vastu-stone/20 rounded-2xl border border-prakash-gold/10"><div className="flex items-center gap-2 mb-2"><div className="w-2 h-2 rounded-full bg-prakash-gold"/><h3 className="font-serif text-lg text-nidra-indigo font-bold">{r.method}</h3></div><p className="text-sm text-nidra-indigo/70 leading-relaxed">{r.desc}</p></div>))}</div></div>

<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-blue-400 to-cyan-600" /><h2 className="font-serif text-2xl sm:text-3xl text-nidra-indigo">Remedies — Neutralising Geopathic Stress Without Moving Your Home</h2></div>
<p>Once geopathic stress zones have been identified and mapped, several precise remedies are available — all non‑invasive, none requiring structural demolition. The VAASTU International portal and Vedic texts converge on the following techniques:</p>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
{[{remedy:'Copper Rod Installation (Geopathic Stress Neutraliser)',detail:'This is the primary Vedic remedy. A copper rod of precise length (typically 18‑24 inches), energised through specific mantras, is driven into the ground at the exact point of the geopathic stress zone. Copper\'s high electrical conductivity effectively creates a Faraday‑type effect, redirecting the harmful radiation. Multiple rods may be required for large zones or intersecting veins.'},{remedy:'Copper Pyramid Placement',detail:'Copper pyramids (typically 3×3 or 5×5 inches), when placed directly above a mapped geopathic stress zone, create a geometric energy field that neutralises harmful radiation. The pyramid shape itself is a proven energy‑amplification structure — the same principle that has been studied by institutions worldwide. Energised copper pyramids are placed under beds, desks, or chairs where people spend the most time.'},{remedy:'Crystal Grid Therapy',detail:'A grid of amethyst, black tourmaline, clear quartz, and rose quartz crystals, arranged in a specific geometric pattern and energised through mantras, absorbs and transmutes geopathic radiation. Black tourmaline is particularly effective for EMF absorption; amethyst calms neurological effects; clear quartz amplifies the corrective energy; rose quartz restores emotional balance.'},{remedy:'Furniture Relocation',detail:'The simplest and most immediate remedy: move the bed, work desk, or favourite chair 3‑5 feet away from the mapped geopathic stress zone. This alone — moving the body\'s nightly resting position by just a meter — has produced dramatic health improvements in multiple documented cases. Children\'s beds are particularly critical to relocate immediately upon detection.'},{remedy:'Brass / Copper Strips Under Flooring',detail:'In new constructions or during renovations, thin strips of brass or copper laid in a grid pattern beneath flooring create a conductive barrier that disperses geopathic radiation across a wider area, reducing its intensity at any single point. This technique, derived from the Vedic practice of Dhatu Sthapna (metal foundation), is the most permanent non‑invasive remedy.'},{remedy:'EMF Shielding',detail:'For man‑made technopathic stress: EMF‑shielding curtains, bed canopies, and paint (containing nickel or copper particles). Switching off Wi‑Fi at night, using wired connections where possible, and keeping mobile phones at least 6 feet from beds reduce the cumulative electromagnetic burden. The EMF Research Foundation recommends a "digital sunset" — switching off all wireless devices 60 minutes before sleep.'},].map((r,i)=>(<div key={i} className="p-4 bg-white/70 rounded-2xl border border-prakash-gold/15"><h3 className="font-serif text-base text-nidra-indigo font-bold mb-2">{r.remedy}</h3><p className="text-sm text-nidra-indigo/70 leading-relaxed">{r.detail}</p></div>))}</div></div>

<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-purple-400 to-fuchsia-500" /><h2 className="font-serif text-2xl sm:text-3xl text-nidra-indigo">Case Study — The Family Whose Children Were Always Sick</h2></div>
<p>In 2019, a family in Noida consulted Vastuvid K.K. Nagaich after three consecutive years in which their two children (aged 5 and 8) were repeatedly hospitalised for respiratory infections. The parents were healthy; the home was new; the Vastu directions were largely correct. Blood tests, allergy panels, and immunological workups revealed nothing abnormal. During the geopathic stress audit, Vastuvid deployed a copper L‑rod dowsing survey and a Gauss meter. Within minutes, a sharp underground water vein crossing was identified directly beneath the children's bedroom — a point where two separate underground streams intersected at approximately 12 feet depth. The Gauss meter reading at the exact intersection point was 143 µT — nearly three times the background level. Both children's beds were positioned directly above this zone. The remedy was precise: a 22‑inch energised copper rod driven into the garden soil at the exact outdoor projection point, a copper pyramid placed under each bed, and both beds shifted 4‑feet northwest — away from the intersection but still within the children's bedroom. Within <strong>six weeks</strong>, both children stopped falling ill. Within <strong>six months</strong>, neither child had been hospitalised — the first time in three years. The family's paediatrician, initially sceptical, acknowledged the outcome and now refers patients with unexplained recurrent illness for geopathic assessment. This case is one of over 200 documented in Vastuvid's clinical records demonstrating that geopathic stress neutralisation produces measurable, often dramatic, health improvements.</p></div>

<div className="mt-12 p-8 bg-gradient-to-br from-vastu-stone/30 to-white rounded-3xl border border-prakash-gold/20"><div className="flex items-center gap-3 mb-4"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-red-500 to-sacred-saffron" /><h2 className="font-serif text-2xl text-nidra-indigo">Conclusion — The Invisible Can Be Neutralised</h2></div>
<p>Geopathic stress is not visible to the naked eye. It will not appear on an X‑ray or a blood panel. But its effects — on sleep, on immunity, on fertility, on the developing bodies of children — are as real as any visible pathogen. From Baron von Pohl's 1929 Vilsbiburg findings to the modern International Association of Geopathology's global database, the evidence converges on a single conclusion: where you sleep matters — not just in terms of comfort, but in terms of the invisible radiation that passes through your body for eight hours every night. The remedies — copper rods, pyramids, crystal grids, strategic furniture relocation — are simple, affordable, and permanently effective. The question is not whether geopathic stress exists. The question is whether it exists beneath your bed.</p>
<p className="font-medium">Vastuvid K.K. Nagaich provides comprehensive geopathic stress audits — including dowsing, Gauss meter mapping, EMF detection, and personalised neutralisation protocols — as part of every residential Vastu consultation. With over 200 documented cases of health transformation following geopathic stress correction, this service has become one of the most requested components of his Vedic practice.</p></div>

</div>
<div className="mt-12 p-6 bg-white/60 backdrop-blur-md rounded-2xl border border-prakash-gold/20 flex items-center gap-4">
<div className="w-14 h-14 rounded-full bg-gradient-to-br from-red-600 to-prakash-gold flex items-center justify-center text-white text-xl font-bold shadow-lg">KK</div>
<div><p className="font-serif text-lg text-nidra-indigo font-bold">Vastuvid KK Nagaich</p><p className="text-sm text-nidra-indigo/60">4th Generation Vastu Guru | MBA | Ex‑CEO | 20+ Years Clinical Practice | 2 Lakh+ Clients Worldwide | Geopathic Stress Specialist</p></div>
</div></div></article></SmoothScroll></>);}
